# Generated by Django 4.0.6 on 2022-07-15 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tur', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Postlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('rasm', models.ImageField(upload_to='media')),
                ('matn', models.TextField()),
                ('aftor', models.ImageField(upload_to='media')),
                ('ism', models.CharField(max_length=40)),
                ('sana', models.DateTimeField(auto_now=True)),
                ('Bolimlar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfiles.bolim')),
            ],
        ),
    ]
