# Generated by Django 4.0.6 on 2022-08-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0002_postlar_vaqt_alter_postlar_sana'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sitelogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('light_rasm', models.ImageField(upload_to='media')),
                ('dark_rasm', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.RenameField(
            model_name='postlar',
            old_name='Bolimlar',
            new_name='bolimlar',
        ),
    ]
