# Generated by Django 4.0.6 on 2022-08-05 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0004_remove_sitelogo_dark_rasm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitelogo',
            old_name='light_rasm',
            new_name='rasm',
        ),
    ]
