# Generated by Django 4.0.6 on 2022-08-05 16:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0005_rename_light_rasm_sitelogo_rasm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitelogo',
            old_name='rasm',
            new_name='rasm_dark',
        ),
        migrations.AddField(
            model_name='sitelogo',
            name='rasm_light',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media'),
            preserve_default=False,
        ),
    ]
