# Generated by Django 4.0.6 on 2022-08-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0006_rename_rasm_sitelogo_rasm_dark_sitelogo_rasm_light'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolimlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('href', models.CharField(max_length=40)),
                ('icon', models.CharField(max_length=40)),
            ],
        ),
    ]
